name: Nightly ETL

on:
  schedule:
    - cron: "7 5 * * *"   # daily 05:07 UTC
  workflow_dispatch: {}

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set OpenAlex polite email
        run: echo "OPENALEX_POLITE_EMAIL=${{ secrets.OPENALEX_POLITE_EMAIL }}" >> $GITHUB_ENV

      - name: Ensure data directory
        run: mkdir -p data

      - name: Run metrics ETL
        env:
          OPENALEX_POLITE_EMAIL: ${{ env.OPENALEX_POLITE_EMAIL }}
        run: |
          python etl/fetch_author_metrics.py             --input data/full_time_faculty.csv             --output data/roster_with_metrics.csv             --email "${{ env.OPENALEX_POLITE_EMAIL }}"             --delay 0.25

      - name: Run works ETL (last 5y, dedup)
        env:
          OPENALEX_POLITE_EMAIL: ${{ env.OPENALEX_POLITE_EMAIL }}
        run: |
          python etl/ucvm_works_wrapper.py
      - name: List ETL outputs
        run: |
          echo "== data =="; ls -la data || true
          echo "== data/compiled =="; ls -la data/compiled || true
          echo "== data/authors_last5y_key_fields =="; ls -la data/authors_last5y_key_fields | sed -n '1,50p' || true
          echo "== data/authors_all_fields =="; ls -la data/authors_all_fields | sed -n '1,50p' || true

      - name: Stamp last update
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" | python - <<'PY'
          import sys, json
          ts = sys.stdin.read().strip()
          with open("data/last_updated.json","w") as f:
              json.dump({"last_updated": ts}, f)
          PY
      
     - name: Commit & push data
        run: |
          set -euxo pipefail
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A data
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "ETL: update data [skip ci]"
          git pull --rebase origin ${{ github.ref_name }} || true
          git push
     
      - name: List ETL outputs
        run: |
          echo "== data =="; ls -la data || true
          echo "== data/compiled =="; ls -la data/compiled || true
          echo "== data/authors_last5y_key_fields =="; ls -la data/authors_last5y_key_fields | sed -n '1,50p' || true
          echo "== data/authors_all_fields =="; ls -la data/authors_all_fields | sed -n '1,50p' || true
