name: Nightly ETL

on:
  schedule:
    - cron: "7 5 * * *"   # daily 05:07 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # fallback builder also uses these explicitly
          pip install requests pandas

      - name: Ensure data directory
        run: mkdir -p data

      - name: Run metrics ETL
        env:
          OPENALEX_POLITE_EMAIL: ${{ secrets.OPENALEX_POLITE_EMAIL }}
        run: |
          set -euxo pipefail
          python etl/fetch_author_metrics.py \
            --input data/full_time_faculty.csv \
            --output data/roster_with_metrics.csv \
            --email "${OPENALEX_POLITE_EMAIL}" \
            --delay 0.25
          echo "Wrote data/roster_with_metrics.csv"
          wc -l data/roster_with_metrics.csv || true
          head -n 3 data/roster_with_metrics.csv || true

      - name: Run works ETL (last 5y, dedup) via wrapper
        env:
          OPENALEX_POLITE_EMAIL: ${{ secrets.OPENALEX_POLITE_EMAIL }}
        run: |
          set -euxo pipefail
          python etl/ucvm_works_wrapper.py || true  # don't fail the job; we'll check outputs

      - name: List ETL outputs (after wrapper)
        run: |
          echo "== data =="; ls -la data || true
          echo "== data/compiled =="; ls -la data/compiled || true
          echo "== data/authors_last5y_key_fields =="; ls -la data/authors_last5y_key_fields | sed -n '1,50p' || true
          echo "== data/authors_all_fields =="; ls -la data/authors_all_fields | sed -n '1,50p' || true

      # Fallback: only build compiled CSVs if they'
