name: Nightly ETL

on:
  schedule:
    - cron: "7 5 * * *"   # daily 05:07 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ensure these are present for the minimal fetcher
          pip install requests pandas

      - name: Echo roster & OA secret presence
        run: |
          echo "== HEAD of data/full_time_faculty.csv =="; head -n 5 data/full_time_faculty.csv || true
          echo "== OA secret set? =="; test -n "${{ secrets.OPENALEX_POLITE_EMAIL }}" && echo "yes" || echo "no"

      - name: Ensure data directory
        run: mkdir -p data

      - name: Run metrics ETL
        env:
          OPENALEX_POLITE_EMAIL: ${{ secrets.OPENALEX_POLITE_EMAIL }}
        run: |
          set -euxo pipefail
          python etl/fetch_author_metrics.py \
            --input data/full_time_faculty.csv \
            --output data/roster_with_metrics.csv \
            --email "${OPENALEX_POLITE_EMAIL}" \
            --delay 0.25
          echo "Wrote data/roster_with_metrics.csv"
          wc -l data/roster_with_metrics.csv || true
          head -n 3 data/roster_with_metrics.csv || true

      - name: Network sanity check (OpenAlex)
        env:
          OPENALEX_POLITE_EMAIL: ${{ secrets.OPENALEX_POLITE_EMAIL }}
        run: |
          set -euxo pipefail
          echo "== OpenAlex /works HEADERS =="
          curl -sI "https://api.openalex.org/works?sample=1&mailto=${OPENALEX_POLITE_EMAIL}" | sed -n '1,20p' || true

      - name: Fetch works (minimal, last 5y)
        env:
          OPENALEX_POLITE_EMAIL: ${{ secrets.OPENALEX_POLITE_EMAIL }}
        run: |
          set -euxo pipefail
          python etl/works_fetch_minimal.py \
            --roster data/roster_with_metrics.csv \
            --outdir data \
            --years 5 \
            --delay 0.2 \
            --email "${OPENALEX_POLITE_EMAIL}"

      - name: List ETL outputs (final)
        run: |
          echo "== data =="; ls -la data || true
          echo "== data/compiled =="; ls -la data/compiled || true | sed -n '1,200p'
          echo "== data/authors_last5y_key_fields =="; ls -la data/authors_last5y_key_fields | sed -n '1,50p' || true
          echo "== data/authors_all_fields =="; ls -la data/authors_all_fields | sed -n '1,50p' || true

      - name: Stamp last update
        run: |
          set -euxo pipefail
          mkdir -p data
          printf '{"last_updated":"%s"}\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > data/last_updated.json
          cat data/last_updated.json

      - name: Commit & push data
        run: |
          set -euxo pipefail
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # Include ALL subfolders under data/
          git add -A data
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "ETL: update data [skip ci]"
          git pull --rebase origin ${{ github.ref_name }} || true
          git push
